"""Generate report/REPORT.md and charts from published JSONL (only source of numbers).

    python report/make_charts.py [--raw results/published] [--out report]
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
# Okabe-Ito colour-blind-safe palette
PALETTE = ["#0072B2", "#E69F00", "#009E73", "#D55E00", "#CC79A7", "#56B4E9", "#F0E442", "#999999"]
OP_NAMES = {
    "OP01": "scan+aggregate", "OP03": "group-by low-card", "OP04": "group-by high-card",
    "OP05": "group-by 3 keys", "OP06": "hash join", "OP07": "star join",
    "OP08": "full sort", "OP09": "top-100 customers", "OP10": "distinct counts", "OP15": "CSV parse",
    "OP19": "NULL handling", "OP21": "decimal vs float", "OP22": "type round trips",
}
TRACK_TITLE = {"L": "Track L - programming languages", "S": "Track S - data systems"}


def ranking_track(r):
    # Ecosystem/tuned algorithms must not displace the original stdlib ranks.
    return (r["track"], r.get("variant", "stdlib") if r["track"] == "L" else "")


def track_title(track):
    name, variant = track
    return TRACK_TITLE[name] + (f" (variant `{variant}`)" if variant else "")


def load(raw: Path) -> list[dict]:
    recs = {}
    for f in sorted(raw.rglob("*.jsonl")):
        for line in f.read_text().splitlines():
            if not line.strip():
                continue
            r = json.loads(line)
            if r["status"] != "ok" or r["op"] == "OP00":
                continue
            key = (r["implementation"], r.get("variant", "stdlib"), r["op"], r["rows"], r["mode"], r["threads"])
            recs[key] = r  # latest wins
    return list(recs.values())


def total(r):  # in-process end-to-end: load + compute
    return (r.get("load_ms") or 0.0) + r["median_ms"]


def dense_rank(items):
    """items: [(name, value, iqr_pct)] -> {name: rank}; ties inside the noise band (max(5%, IQR))."""
    items = sorted(items, key=lambda x: x[1])
    ranks, rank, anchor = {}, 0, None
    for name, v, iqr in items:
        if anchor is None or v > anchor[0] * (1 + max(0.05, iqr / 100, anchor[1] / 100)):
            rank += 1
            anchor = (v, iqr)
        ranks[name] = rank
    return ranks


def fmt_ms(x):
    if x is None:
        return "-"
    return f"{x:,.1f}" if x < 1000 else f"{x / 1000:,.2f} s"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", default=str(ROOT / "results" / "published"))
    ap.add_argument("--out", default=str(ROOT / "report"))
    a = ap.parse_args(argv)
    out = Path(a.out)
    (out / "charts").mkdir(parents=True, exist_ok=True)
    recs = load(Path(a.raw))
    if not recs:
        raise SystemExit("no ok records found")
    env = recs[0]["env"]
    impls = sorted({r["implementation"] for r in recs})
    color = {n: PALETTE[i % len(PALETTE)] for i, n in enumerate(impls)}
    sizes = sorted({r["rows"] for r in recs})
    lines = ["# Benchmark report (generated - do not edit by hand)", "",
             f"Generated by `report/make_charts.py` from `{Path(a.raw).name}/**/*.jsonl`. **Rankings are per operation, per size, per mode "
             "and per thread count; tracks and Track L variants are ranked separately.** There is no overall winner.", "",
             "## Environment", "",
             f"{env['cpu']}, {env['cores']} cores, {env['ram_gb']} GB RAM, {env['os']}; container limits: "
             f"{env.get('container_limits') or 'none'}; single-thread runs pinned with `taskset`; page cache: warm "
             "(data generated just before the runs). Published campaigns may differ in environment - see *Threats to validity*.", "",
             "## How to read the tables", "",
             "* `load` = read+parse into memory (Track L) or table load / file scan (Track S); `compute` = the operation; "
             "values are medians of the timed runs (run/warm-up counts are recorded in the source JSONL). OP15 reports parsing as `compute` (load = 0).",
             "* Track L `stdlib` is the original baseline; `tuned` uses dependency-free custom containers/sort; "
             "`ecosystem` uses named libraries. Each variant has its own table, chart and ranks.",
             "* **Rank is by `load + compute`** (in-process end-to-end). Ranking by `compute` alone would reward "
             "implementations that move work into `load` (e.g. dictionary-encoding strings while parsing). The compute-only rank is shown in parentheses.",
             "* Dense ranks; entries within max(5%, IQR) of the rank's anchor share the rank. `noisy` = IQR/median > 10%.",
             "* `RSS` = peak resident memory of the process (includes the language/engine runtime).", ""]
    by_cfg = defaultdict(list)
    for r in recs:
        by_cfg[(ranking_track(r), r["rows"], r["mode"], r["threads"], r["op"])].append(r)

    for rows in sizes:
        label = {10**3: "1k", 10**4: "10k", 10**6: "1M", 10**7: "10M"}.get(rows, str(rows))
        lines += [f"## {label} rows", ""]
        for track in sorted({ranking_track(r) for r in recs}):
            cfgs = sorted({k[2:4] for k in by_cfg if k[0] == track and k[1] == rows})
            if not cfgs:
                continue
            lines += [f"### {track_title(track)}", ""]
            for mode, threads in cfgs:
                ops = sorted({k[4] for k in by_cfg if k[:4] == (track, rows, mode, threads)})
                lines += [f"#### {mode}, {threads} thread{'s' if threads > 1 else ''}", "",
                          "| op | " + " | ".join(impls_in := sorted({r['implementation'] for o in ops for r in by_cfg[(track, rows, mode, threads, o)]})) + " |",
                          "|---|" + "---|" * len(impls_in)]
                for op in ops:
                    group = by_cfg[(track, rows, mode, threads, op)]
                    rk_total = dense_rank([(r["implementation"], total(r), r.get("iqr_pct") or 0) for r in group])
                    rk_comp = dense_rank([(r["implementation"], r["median_ms"], r.get("iqr_pct") or 0) for r in group])
                    cells = []
                    gm = {r["implementation"]: r for r in group}
                    for n in impls_in:
                        r = gm.get(n)
                        if r is None:
                            cells.append("-")
                            continue
                        cells.append(f"**#{rk_total[n]}** ({rk_comp[n]}) {fmt_ms(total(r))} "
                                     f"<sub>load {fmt_ms(r.get('load_ms'))} + compute {fmt_ms(r['median_ms'])}; "
                                     f"{r['peak_rss_mb']:.0f} MB{'; noisy' if r.get('noisy') else ''}</sub>")
                    lines.append(f"| {op} {OP_NAMES.get(op, '')} | " + " | ".join(cells) + " |")
                lines.append("")
            # chart: bars per op for each (mode, threads), log scale
            n = len(cfgs)
            fig, axes = plt.subplots(1, n, figsize=(5.2 * n + 2, 4.6), squeeze=False)
            for ax, (mode, threads) in zip(axes[0], cfgs):
                ops = sorted({k[4] for k in by_cfg if k[:4] == (track, rows, mode, threads)})
                present = sorted({r["implementation"] for o in ops for r in by_cfg[(track, rows, mode, threads, o)]})
                w = 0.8 / max(len(present), 1)
                for i, name in enumerate(present):
                    ys = []
                    for op in ops:
                        r = next((x for x in by_cfg[(track, rows, mode, threads, op)] if x["implementation"] == name), None)
                        ys.append(total(r) if r else float("nan"))
                    ax.bar([j + i * w for j in range(len(ops))], ys, w, label=name, color=color[name])
                ax.set_yscale("log")
                ax.set_xticks([j + 0.4 - w / 2 for j in range(len(ops))])
                ax.set_xticklabels(ops, rotation=45, fontsize=8)
                ax.set_ylabel("load + compute, ms (log)")
                ax.set_title(f"{mode}, {threads}t", fontsize=10)
                ax.grid(axis="y", alpha=0.3)
            axes[0][-1].legend(fontsize=8, loc="center left", bbox_to_anchor=(1.01, 0.5))
            fig.suptitle(f"{track_title(track).replace('`', '')} - {label} rows (lower is better)", fontsize=10)
            fig.tight_layout()
            suffix = f"_{track[1]}" if track[1] not in ("", "stdlib") else ""
            fn = f"charts/{track[0]}{suffix}_{label}_bars.png"
            fig.savefig(out / fn, dpi=110)
            plt.close(fig)
            lines += [f"![{track_title(track)} {label}]({fn})", ""]
    # memory table at the largest size
    big = sizes[-1]
    lines += ["## Peak memory at the largest size", "", "| implementation | mode | threads | min RSS MB | max RSS MB |", "|---|---|---|---|---|"]
    mem = defaultdict(list)
    for r in recs:
        if r["rows"] == big:
            mem[(r["implementation"], r["mode"], r["threads"])].append(r["peak_rss_mb"])
    for (n, m, t), v in sorted(mem.items()):
        lines.append(f"| {n} | {m} | {t} | {min(v):.0f} | {max(v):.0f} |")
    lines += ["", "## Threats to validity", "",
              "* Single machine / container; 4 cores shared with the OS; no repeated campaigns on different hardware.",
              "* Campaigns are not a controlled comparison across machines. Roadmap item 3 records use one timed run, "
              "no warm-up at 1k/10k/1M: correctness evidence only, not publication-grade performance evidence.",
              "* Few timed runs (5 in the earlier 1M/10M campaigns, 3 for the Python/SQLite 10M subsets); `noisy` flags mark unstable cells.",
              "* Implementation skill bias: each implementation was written once; see `languages/*/README.md` and `systems/*/README.md` for choices.",
              "* Load/compute split is implementation-defined (see rank rule above); engines differ in streaming semantics "
              "(DuckDB/Polars scan all files in one query and ignore `--chunk-rows`).",
              "* Python/SQLite 10M cover only a subset of operations; nothing above 10M rows has been run.",
              "* Library versions and compilers are recorded in each record's `toolchain` field.", ""]
    (out / "REPORT.md").write_text("\n".join(lines))
    print(f"wrote {out / 'REPORT.md'} ({len(recs)} records, {len(sizes)} sizes)")


if __name__ == "__main__":
    main()
