#!/usr/bin/env python3
"""Read docs/data-types/conformance-output/<lang>.txt and write MATRIX.md (keys x languages).

Also checks every output has the full key set (exit 1 if not) and lists keys whose values differ.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "docs", "data-types", "conformance-output")
ORDER = ["cpp", "rust", "go", "java", "javascript", "typescript", "python",
         "csharp", "julia", "swift", "kotlin", "scala", "r"]


def load(path):
    d, order = {}, []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or "=" not in line:
                continue
            k, v = line.split("=", 1)
            d[k] = v
            order.append(k)
    return d, order


def main():
    data, keyorder = {}, []
    for lang in ORDER:
        p = os.path.join(OUT, lang + ".txt")
        if os.path.exists(p):
            data[lang], order = load(p)
            for k in order:
                if k not in keyorder:
                    keyorder.append(k)
    langs = [l for l in ORDER if l in data]
    not_run = [l for l in ORDER if l not in data]
    problems = []
    for l in langs:
        missing = [k for k in keyorder if k not in data[l]]
        if missing:
            problems.append(f"{l}: missing keys {missing}")
    skip = {"lang", "version", "char_meaning"}
    differing = [k for k in keyorder if k not in skip and len({data[l].get(k, "<missing>") for l in langs}) > 1]
    same = [k for k in keyorder if k not in skip and k not in differing]

    esc = lambda s: s.replace("|", "\\|")
    lines = ["# Conformance matrix", "",
             "Generated by `conformance/compare.py` from the `<lang>.txt` files in this directory.", "",
             f"Languages run: {', '.join(langs)}.  ",
             f"Not run (toolchain unavailable): {', '.join(not_run) if not_run else 'none'}.", ""]
    lines += ["## Keys whose values differ across languages", "",
              "| key | " + " | ".join(langs) + " |", "|---|" + "---|" * len(langs)]
    for k in differing:
        lines.append(f"| `{k}` | " + " | ".join(esc(data[l].get(k, "-")) for l in langs) + " |")
    lines += ["", "## Keys identical in every language that ran", "",
              "| key | value |", "|---|---|"]
    for k in same:
        lines.append(f"| `{k}` | {esc(data[langs[0]][k])} |")
    lines += ["", "## Identification", "", "| language | version | char meaning |", "|---|---|---|"]
    for l in langs:
        lines.append(f"| {l} | {esc(data[l].get('version', '-'))} | {esc(data[l].get('char_meaning', '-'))} |")
    lines.append("")
    with open(os.path.join(OUT, "MATRIX.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"MATRIX.md written: {len(langs)} languages, {len(keyorder)} keys, {len(differing)} differing")
    print("differing keys:", ", ".join(differing))
    if problems:
        print("\n".join(problems))
        sys.exit(1)


if __name__ == "__main__":
    main()
