#!/usr/bin/env bash
# Build (if needed) and run every conformance probe; fully offline (no package downloads).
# Output: docs/data-types/conformance-output/<lang>.txt, conformance/STATUS.md, MATRIX.md (via compare.py).
set -u
ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="$ROOT/../docs/data-types/conformance-output"
BUILD="$ROOT/.build"
TSV="$ROOT/.status.tsv"
mkdir -p "$OUT" "$BUILD"
: > "$TSV"
export GOFLAGS=-mod=mod GOPROXY=off GOTOOLCHAIN=local CGO_ENABLED=0
unset JAVA_TOOL_OPTIONS   # avoid the "Picked up ..." banner

record() { printf '%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" >> "$TSV"; }
first_line() { "$@" 2>&1 | head -n1 | tr '\t' ' '; }

# run_lang <lang> <tool-to-detect> <version-cmd...> -- ; uses functions build_<lang> / run_<lang>
run_lang() {
  local lang="$1" tool="$2"; shift 2
  local out="$OUT/$lang.txt"
  rm -f "$out"
  if ! command -v "$tool" >/dev/null 2>&1; then
    record "$lang" not_run "-" "toolchain not installed ($tool not found)"
    echo "[$lang] not_run ($tool missing)"; return
  fi
  local ver; ver="$("$@" 2>&1 | grep -v "^Picked up" | head -n1 | tr '\t' ' ')"
  local log="$BUILD/$lang.log"
  if ! ( build_"$lang" ) >"$log" 2>&1; then
    record "$lang" failed "$ver" "build failed (see conformance/.build/$lang.log)"
    echo "[$lang] BUILD FAILED"; return
  fi
  if ( run_"$lang" ) >"$out.tmp" 2>>"$log"; then
    mv "$out.tmp" "$out"; record "$lang" ok "$ver" "-"; echo "[$lang] ok"
  else
    rm -f "$out.tmp"; record "$lang" failed "$ver" "run failed (see conformance/.build/$lang.log)"
    echo "[$lang] RUN FAILED"
  fi
}

build_cpp()  { g++ -std=c++20 -O0 -o "$BUILD/cpp" "$ROOT/cpp/main.cpp"; }
run_cpp()    { "$BUILD/cpp"; }
build_rust() { rustc -C opt-level=0 -C debug-assertions=on -C overflow-checks=on -o "$BUILD/rust" "$ROOT/rust/main.rs"; }
run_rust()   { "$BUILD/rust"; }
build_go()   { (cd "$ROOT/go" && go build -o "$BUILD/go" .); }
run_go()     { "$BUILD/go"; }
build_java() { mkdir -p "$BUILD/java" && javac -d "$BUILD/java" "$ROOT/java/Main.java"; }
run_java()   { java -cp "$BUILD/java" Main; }
build_javascript() { :; }
run_javascript()   { node "$ROOT/javascript/main.js"; }
build_typescript() { rm -rf "$BUILD/typescript"; tsc -p "$ROOT/typescript"; }
run_typescript()   { TSC_VERSION="$(tsc --version | awk '{print $2}')" node "$BUILD/typescript/main.js"; }
build_python() { :; }
run_python()   { python3 "$ROOT/python/main.py"; }
build_csharp() { (cd "$ROOT/csharp" && dotnet build -c Release -o "$BUILD/csharp" --no-restore -nologo); }
run_csharp()   { dotnet "$BUILD/csharp/conformance.dll"; }
build_julia() { :; }
run_julia()   { julia "$ROOT/julia/main.jl"; }
build_swift() { swiftc -o "$BUILD/swift" "$ROOT/swift/main.swift"; }
run_swift()   { "$BUILD/swift"; }
build_kotlin() { kotlinc "$ROOT/kotlin/Main.kt" -include-runtime -d "$BUILD/kotlin.jar"; }
run_kotlin()   { java -jar "$BUILD/kotlin.jar"; }
build_scala() { :; }
run_scala()   { scala-cli run --offline "$ROOT/scala/Main.scala"; }
build_r() { :; }
run_r()   { Rscript "$ROOT/r/main.R"; }

run_lang cpp        g++      g++ --version
run_lang rust       rustc    rustc --version
run_lang go         go       go version
run_lang java       javac    java -version
run_lang javascript node     node --version
run_lang typescript tsc      tsc --version
run_lang python     python3  python3 --version
run_lang csharp     dotnet   dotnet --version
run_lang julia      julia    julia --version
run_lang swift      swiftc   swiftc --version
run_lang kotlin     kotlinc  kotlinc -version
run_lang scala      scala-cli scala-cli version
run_lang r          Rscript  Rscript --version

# STATUS.md (generated)
{
  echo "# Conformance status"
  echo
  echo "Generated by \`conformance/run_all.sh\`. Do not edit by hand."
  echo
  echo "| language | status | toolchain version | reason |"
  echo "|---|---|---|---|"
  while IFS=$'\t' read -r l s v r; do echo "| $l | $s | $v | $r |"; done < "$TSV"
} > "$ROOT/STATUS.md"

python3 "$ROOT/compare.py"
