#!/usr/bin/env python3
"""Validate types.yaml and generate the data-type comparison markdown.

Usage:
    python3 docs/data-types/build.py            # validate + (re)write markdown
    python3 docs/data-types/build.py --check    # validate + fail if files on disk differ

Only stdlib and PyYAML are required.
"""
import argparse
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
YAML_PATH = HERE / "types.yaml"

CATEGORIES = [
    ("integers", "Integers", "Signed and unsigned fixed-width integers."),
    ("floating-point-and-decimal", "Floating point and decimal", "IEEE-754 binary floats and exact decimal / arbitrary precision."),
    ("text-and-binary", "Text, binary and boolean", "Boolean, character, string and byte arrays."),
    ("temporal", "Temporal types", "Date, time of day and timestamps."),
    ("nullability-and-errors", "Nullability and errors", "Optional values and error/result modeling."),
    ("collections", "Collections", "Arrays, lists, maps and sets."),
    ("composite-types", "Composite types", "Tuples, structs/records, classes/objects and enumerations."),
]
FIELD_LABELS = {
    "type_name": "Type name",
    "size_bytes": "In-memory size",
    "width": "Width",
    "null_support": "Null support",
    "primitive_or_object": "Primitive / object",
    "de_use": "Typical DE use",
    "conversion_risks": "Conversion risks",
    "precision_limits": "Precision limits",
    "performance_notes": "Performance notes",
}
UNVERIFIED = "unverified"
BANNER = "<!-- GENERATED by docs/data-types/build.py from types.yaml. Do not edit by hand. -->\n"


def load():
    with open(YAML_PATH, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def validate(doc):
    errors = []
    fields = doc.get("fields") or []
    if list(fields) != list(FIELD_LABELS):
        errors.append(f"fields list must equal {list(FIELD_LABELS)}; got {fields}")
    langs = doc.get("languages") or []
    lang_ids = [l.get("id") for l in langs]
    if len(set(lang_ids)) != len(lang_ids):
        errors.append("duplicate language ids")
    for l in langs:
        for key in ("id", "name", "kind", "sources"):
            if not l.get(key):
                errors.append(f"language {l.get('id')}: missing '{key}'")
        if l.get("kind") not in ("language", "reference"):
            errors.append(f"language {l.get('id')}: kind must be language|reference")
    cat_ids = {c[0] for c in CATEGORIES}
    concepts = doc.get("concepts") or []
    cids = [c.get("id") for c in concepts]
    dup = {c for c in cids if cids.count(c) > 1}
    if dup:
        errors.append(f"duplicate concept ids: {sorted(dup)}")
    for c in concepts:
        cid = c.get("id")
        for key in ("id", "title", "category", "description", "cells"):
            if not c.get(key):
                errors.append(f"concept {cid}: missing '{key}'")
        if c.get("category") not in cat_ids:
            errors.append(f"concept {cid}: unknown category {c.get('category')}")
        cells = c.get("cells") or {}
        for extra in set(cells) - set(lang_ids):
            errors.append(f"concept {cid}: unknown language '{extra}'")
        for lid in lang_ids:
            cell = cells.get(lid)
            if cell is None:
                errors.append(f"MISSING cell: concept={cid} language={lid} (all fields)")
                continue
            for f in FIELD_LABELS:
                v = cell.get(f)
                if not isinstance(v, str) or not v.strip():
                    errors.append(f"MISSING field: concept={cid} language={lid} field={f}")
            for f in set(cell) - set(FIELD_LABELS):
                errors.append(f"concept={cid} language={lid}: unknown field {f}")
    return errors


def esc(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def render_category(doc, cat):
    cid, title, blurb = cat
    langs = doc["languages"]
    out = [BANNER, f"# {title}\n", f"{blurb} Part of the [data-type comparison](index.md).\n",
           "Fields prefixed `unverified:` contain at least one claim not confirmed against primary documentation. "
           "Equivalent names do not imply identical memory layout or behavior; see [equivalence-is-not-identity.md](equivalence-is-not-identity.md).\n"]
    for c in doc["concepts"]:
        if c["category"] != cid:
            continue
        out.append(f"## {c['title']}\n")
        out.append(f"{c['description']}\n")
        head = ["Language"] + [FIELD_LABELS[f] for f in FIELD_LABELS]
        out.append("| " + " | ".join(head) + " |")
        out.append("|" + "|".join(["---"] * len(head)) + "|")
        for l in langs:
            cell = c["cells"][l["id"]]
            row = [f"**{l['name']}**"] + [esc(cell[f]) for f in FIELD_LABELS]
            out.append("| " + " | ".join(row) + " |")
        out.append("")
    return "\n".join(out) + "\n"


def count_unverified(doc):
    n = 0
    per_concept = {}
    for c in doc["concepts"]:
        k = 0
        for cell in c["cells"].values():
            for f in FIELD_LABELS:
                if UNVERIFIED in cell[f].lower():
                    k += 1
        per_concept[c["id"]] = k
        n += k
    return n, per_concept


def render_index(doc):
    langs = doc["languages"]
    total_cells = len(doc["concepts"]) * len(langs)
    n_unv, per = count_unverified(doc)
    out = [BANNER, "# Data-type comparison: index\n",
           "Generated from [`types.yaml`](types.yaml) (single source of truth). "
           "**Headline caveat: equivalent type names do not imply identical memory layout or behavior.** "
           "See [equivalence-is-not-identity.md](equivalence-is-not-identity.md) and [conversion-matrix.md](conversion-matrix.md).\n",
           f"Coverage: {len(doc['concepts'])} concepts x {len(langs)} columns = {total_cells} cells x {len(FIELD_LABELS)} fields. "
           f"Fields flagged `unverified`: {n_unv}.\n",
           "## Categories\n"]
    for cid, title, blurb in CATEGORIES:
        out.append(f"### [{title}]({cid}.md)\n")
        out.append(f"{blurb}\n")
        for c in doc["concepts"]:
            if c["category"] == cid:
                out.append(f"- [{c['title']}]({cid}.md#{anchor(c['title'])}) ({per[c['id']]} unverified fields)")
        out.append("")
    out.append("## Columns\n")
    out.append("| Id | Column | Kind |\n|---|---|---|")
    for l in langs:
        out.append(f"| {l['id']} | {l['name']} | {l['kind']} |")
    out.append("")
    out.append("## Fields documented per cell\n")
    for f, label in FIELD_LABELS.items():
        out.append(f"- `{f}`: {label}")
    out.append("")
    out.append("## Other documents\n")
    out.append("- [README.md](README.md): reading guide and how to rebuild")
    out.append("- [equivalence-is-not-identity.md](equivalence-is-not-identity.md): runnable examples where equivalent names behave differently")
    out.append("- [conversion-matrix.md](conversion-matrix.md): Dataset A conversion risks per language")
    out.append("- `conformance-output/`: actual sizeof/overflow/0.1+0.2 output from the conformance tests (written by the conformance suite)")
    out.append("")
    out.append("## Sources (documentation roots)\n")
    for l in langs:
        out.append(f"### {l['name']}\n")
        for s in l["sources"]:
            out.append(f"- <{s}>")
        out.append("")
    return "\n".join(out) + "\n"


def anchor(title):
    import re
    a = title.lower()
    a = re.sub(r"[^\w\s-]", "", a)
    return re.sub(r"\s", "-", a)


def generate(doc):
    files = {f"{cid}.md": render_category(doc, (cid, t, b)) for cid, t, b in CATEGORIES}
    files["index.md"] = render_index(doc)
    return files


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit non-zero if generated markdown differs from disk")
    args = ap.parse_args()
    doc = load()
    errors = validate(doc)
    if errors:
        print(f"VALIDATION FAILED: {len(errors)} problem(s)", file=sys.stderr)
        for e in errors:
            print("  - " + e, file=sys.stderr)
        return 1
    files = generate(doc)
    n_unv, _ = count_unverified(doc)
    if args.check:
        bad = []
        for name, content in files.items():
            p = HERE / name
            if not p.exists():
                bad.append(f"{name}: missing on disk")
            elif p.read_text(encoding="utf-8") != content:
                bad.append(f"{name}: differs from generated output")
        if bad:
            print("CHECK FAILED (run: python3 docs/data-types/build.py):", file=sys.stderr)
            for b in bad:
                print("  - " + b, file=sys.stderr)
            return 1
        print(f"check ok: {len(files)} files up to date; {n_unv} unverified fields")
        return 0
    for name, content in files.items():
        (HERE / name).write_text(content, encoding="utf-8")
    print(f"validated {len(doc['concepts'])} concepts x {len(doc['languages'])} columns; wrote {len(files)} files; {n_unv} unverified fields")
    return 0


if __name__ == "__main__":
    sys.exit(main())
